
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        KillTarget = _buf.ReadInt();
        EnemySpeed = _buf.ReadFloat();
        EnemySpawnInterval = _buf.ReadFloat();
    }

    public static Level DeserializeLevel(ByteBuf _buf)
    {
        return new level.Level(_buf);
    }

    /// <summary>
    /// level_id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// level_name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// kill_target
    /// </summary>
    public readonly int KillTarget;
    /// <summary>
    /// enemy_speed
    /// </summary>
    public readonly float EnemySpeed;
    /// <summary>
    /// spawn_interval
    /// </summary>
    public readonly float EnemySpawnInterval;
   
    public const int __ID__ = 685080698;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "killTarget:" + KillTarget + ","
        + "enemySpeed:" + EnemySpeed + ","
        + "enemySpawnInterval:" + EnemySpawnInterval + ","
        + "}";
    }
}
}

