
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.level
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelName = _buf.ReadString();
        EnergyCost = _buf.ReadInt();
        PassScore = _buf.ReadInt();
        PassKillCount = _buf.ReadInt();
    }

    public static Level DeserializeLevel(ByteBuf _buf)
    {
        return new level.Level(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡名称
    /// </summary>
    public readonly string LevelName;
    /// <summary>
    /// 体力消耗
    /// </summary>
    public readonly int EnergyCost;
    /// <summary>
    /// 通关分数
    /// </summary>
    public readonly int PassScore;
    /// <summary>
    /// 通关杀敌数
    /// </summary>
    public readonly int PassKillCount;
   
    public const int __ID__ = 685080698;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelName:" + LevelName + ","
        + "energyCost:" + EnergyCost + ","
        + "passScore:" + PassScore + ","
        + "passKillCount:" + PassKillCount + ","
        + "}";
    }
}
}

