
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Chapter : Luban.BeanBase
{
    public Chapter(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Prefab = _buf.ReadString();
    }

    public static Chapter DeserializeChapter(ByteBuf _buf)
    {
        return new Chapter(_buf);
    }

    /// <summary>
    /// 章节
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 预制体名
    /// </summary>
    public readonly string Prefab;
   
    public const int __ID__ = -1891298259;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Prefab:" + Prefab + ","
        + "}";
    }
}

}

