
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class FruitConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Fruit> _dataMap;
    private readonly System.Collections.Generic.List<Fruit> _dataList;
    
    public FruitConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Fruit>();
        _dataList = new System.Collections.Generic.List<Fruit>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fruit _v;
            _v = global::GameConfig.Fruit.DeserializeFruit(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Fruit> DataMap => _dataMap;
    public System.Collections.Generic.List<Fruit> DataList => _dataList;

    public Fruit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fruit Get(int key) => _dataMap[key];
    public Fruit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

