
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Fruit : Luban.BeanBase
{
    public Fruit(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Point = _buf.ReadInt();
        Icon = _buf.ReadString();
    }

    public static Fruit DeserializeFruit(ByteBuf _buf)
    {
        return new Fruit(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 得分值
    /// </summary>
    public readonly int Point;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = 68158452;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Point:" + Point + ","
        + "Icon:" + Icon + ","
        + "}";
    }
}

}

