
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GameConfigs : Luban.BeanBase
{
    public GameConfigs(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        IntValue = _buf.ReadInt();
        StringValue = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ListInt = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ListInt.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ListString = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ListString.Add(_e0);}}
    }

    public static GameConfigs DeserializeGameConfigs(ByteBuf _buf)
    {
        return new GameConfigs(_buf);
    }

    public readonly string Id;
    /// <summary>
    /// 整数
    /// </summary>
    public readonly int IntValue;
    /// <summary>
    /// 字符串
    /// </summary>
    public readonly string StringValue;
    /// <summary>
    /// 整数数组
    /// </summary>
    public readonly System.Collections.Generic.List<int> ListInt;
    /// <summary>
    /// 字符串数组
    /// </summary>
    public readonly System.Collections.Generic.List<string> ListString;
   
    public const int __ID__ = -1809521409;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "IntValue:" + IntValue + ","
        + "StringValue:" + StringValue + ","
        + "ListInt:" + Luban.StringUtil.CollectionToString(ListInt) + ","
        + "ListString:" + Luban.StringUtil.CollectionToString(ListString) + ","
        + "}";
    }
}

}

