
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class GameConfigsConfig
{
    private readonly System.Collections.Generic.Dictionary<string, GameConfigs> _dataMap;
    private readonly System.Collections.Generic.List<GameConfigs> _dataList;
    
    public GameConfigsConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, GameConfigs>();
        _dataList = new System.Collections.Generic.List<GameConfigs>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameConfigs _v;
            _v = global::GameConfig.GameConfigs.DeserializeGameConfigs(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, GameConfigs> DataMap => _dataMap;
    public System.Collections.Generic.List<GameConfigs> DataList => _dataList;

    public GameConfigs GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameConfigs Get(string key) => _dataMap[key];
    public GameConfigs this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

