
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class HoleLevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, HoleLevel> _dataMap;
    private readonly System.Collections.Generic.List<HoleLevel> _dataList;
    
    public HoleLevelConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HoleLevel>();
        _dataList = new System.Collections.Generic.List<HoleLevel>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            HoleLevel _v;
            _v = global::GameConfig.HoleLevel.DeserializeHoleLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HoleLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<HoleLevel> DataList => _dataList;

    public HoleLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HoleLevel Get(int key) => _dataMap[key];
    public HoleLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

