
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class HoleLevel : Luban.BeanBase
{
    public HoleLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Size = _buf.ReadInt();
        Exp = _buf.ReadInt();
        Speed = _buf.ReadInt();
    }

    public static HoleLevel DeserializeHoleLevel(ByteBuf _buf)
    {
        return new HoleLevel(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 大小*100
    /// </summary>
    public readonly int Size;
    /// <summary>
    /// 所需经验值（总额）
    /// </summary>
    public readonly int Exp;
    /// <summary>
    /// 速度*100
    /// </summary>
    public readonly int Speed;
   
    public const int __ID__ = -1078276476;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "size:" + Size + ","
        + "exp:" + Exp + ","
        + "speed:" + Speed + ","
        + "}";
    }
}

}

