
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public GameConfigsConfig GameConfigsConfig {get; }
    public HoleLevelConfig HoleLevelConfig {get; }
    public FruitConfig FruitConfig {get; }
    public ChapterConfig ChapterConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        GameConfigsConfig = new GameConfigsConfig(loader("GameConfigsConfig"));
        HoleLevelConfig = new HoleLevelConfig(loader("HoleLevelConfig"));
        FruitConfig = new FruitConfig(loader("FruitConfig"));
        ChapterConfig = new ChapterConfig(loader("ChapterConfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GameConfigsConfig.ResolveRef(this);
        HoleLevelConfig.ResolveRef(this);
        FruitConfig.ResolveRef(this);
        ChapterConfig.ResolveRef(this);
    }
}

}
