
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.energy
{
public sealed partial class Energy : Luban.BeanBase
{
    public Energy(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MaxEnergy = _buf.ReadInt();
        RecoverRate = _buf.ReadInt();
        CostPerLevel = _buf.ReadInt();
    }

    public static Energy DeserializeEnergy(ByteBuf _buf)
    {
        return new energy.Energy(_buf);
    }

    /// <summary>
    /// 体力id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大体力
    /// </summary>
    public readonly int MaxEnergy;
    /// <summary>
    /// 恢复速率(秒/点)
    /// </summary>
    public readonly int RecoverRate;
    /// <summary>
    /// 每关卡消耗
    /// </summary>
    public readonly int CostPerLevel;
   
    public const int __ID__ = -1387845426;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maxEnergy:" + MaxEnergy + ","
        + "recoverRate:" + RecoverRate + ","
        + "costPerLevel:" + CostPerLevel + ","
        + "}";
    }
}
}

