
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.energy
{
public partial class TbEnergy
{
    private readonly System.Collections.Generic.Dictionary<int, energy.Energy> _dataMap;
    private readonly System.Collections.Generic.List<energy.Energy> _dataList;
    
    public TbEnergy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, energy.Energy>(n);
        _dataList = new System.Collections.Generic.List<energy.Energy>(n);
        for(int i = n ; i > 0 ; --i)
        {
            energy.Energy _v;
            _v = global::GameConfig.energy.Energy.DeserializeEnergy(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, energy.Energy> DataMap => _dataMap;
    public System.Collections.Generic.List<energy.Energy> DataList => _dataList;

    public energy.Energy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public energy.Energy Get(int key) => _dataMap[key];
    public energy.Energy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

